"""
Plot script for the §4 cross-fitting / DML simulation figures.

Reads the saved simulation results from
    Data/InferenceOverviewSimExtended.csv

and writes the three slide figures to Slides/figures/:
    Slide_26.png : nonlinear DGP, Oracle vs. Full-sample DNN
                       (overfitting-bias panel)
    Slide_30.png : nonlinear DGP, Oracle vs. DML(DNN) vs. Full-sample DNN
                       (cross-fitting fixes the bias)
    Slide_34.png : 2-panel "match learner to DGP"
                         left  = linear    DGP (Oracle, DML(Lasso), DML(DNN))
                         right = nonlinear DGP (Oracle, DML(Lasso), DML(DNN))

Aesthetic conventions (set per Christian's session-18 feedback):
  - No panel titles.
  - Common x-axis (0.10, 0.90) and common bin edges across every panel.
  - Legend placed below the x-axis as a horizontal strip, no frame.
  - Vertical dashed line at the true alpha_0 = 0.5 for orientation.

The CSV is generated by InferenceOverviewSimExtended.py; rerunning the
simulation is not required to regenerate the figures.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


HERE      = Path(__file__).resolve().parent
DATA_CSV  = (HERE.parent / "Data" / "InferenceOverviewSimExtended.csv").resolve()
PLOTDIR   = (HERE.parent / "Slides" / "figures").resolve()

ALPHA0    = 0.5

# Common x-axis and bins: data range across all series is [0.13, 0.85];
# pad lightly to [0.10, 0.90]; bin width 0.02 puts alpha_0 on a bin edge
# and gives 40 bins, which is dense enough for n = 1000 reps without
# being noisy.
XLIM      = (0.10, 0.90)
BINS      = np.arange(XLIM[0], XLIM[1] + 1e-9, 0.02)

# Palette: Oracle (green) is the benchmark; DML(Lasso) (orange) and
# DML(DNN) (red) are the two estimators; full-sample DNN (steel blue)
# is the "do-not-do-this" baseline. Truth line is black so it does not
# compete with DML(DNN)'s red.
C_ORACLE  = "#3a8c3a"
C_LASSO   = "#d97a00"
C_DNN     = "#b03030"
C_FULL    = "#2a4d8f"
C_TRUTH   = "black"

ALPHA_FILL = 0.62

# Slide-friendly typography.
plt.rcParams.update({
    "font.size":        13,
    "axes.labelsize":   14,
    "axes.titlesize":   14,
    "xtick.labelsize":  12,
    "ytick.labelsize":  12,
    "legend.fontsize":  12,
})


def _draw_hist(ax, values, color, label):
    ax.hist(values, bins=BINS, color=color, alpha=ALPHA_FILL,
            label=label, edgecolor="white", linewidth=0.3)


def _truth_line(ax):
    ax.axvline(ALPHA0, color=C_TRUTH, linestyle="--", linewidth=1.2)


def _style_axes(ax):
    ax.set_xlim(*XLIM)
    ax.set_xlabel(r"$\hat\alpha$")
    ax.set_ylabel("Count")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def _legend_below(fig, handles, labels, n_panels=1, y=-0.02):
    fig.legend(handles, labels,
               loc="lower center",
               bbox_to_anchor=(0.5, y),
               ncol=len(labels),
               frameon=False,
               handlelength=1.6,
               columnspacing=2.0)


def plot_slide_26(df, savepath):
    fig, ax = plt.subplots(figsize=(8.0, 4.6))
    _draw_hist(ax, df["nl_oracle"],   C_ORACLE, "Oracle")
    _draw_hist(ax, df["nl_full_dnn"], C_FULL,   "Full sample (DNN)")
    _truth_line(ax)
    _style_axes(ax)
    handles, labels = ax.get_legend_handles_labels()
    fig.tight_layout(rect=(0, 0.08, 1, 1))
    _legend_below(fig, handles, labels, n_panels=1, y=0.00)
    fig.savefig(savepath, dpi=200, bbox_inches="tight")
    plt.close(fig)


def plot_slide_30(df, savepath):
    fig, ax = plt.subplots(figsize=(8.0, 4.6))
    _draw_hist(ax, df["nl_oracle"],   C_ORACLE, "Oracle")
    _draw_hist(ax, df["nl_dml_dnn"],  C_DNN,    "DML (DNN)")
    _draw_hist(ax, df["nl_full_dnn"], C_FULL,   "Full sample (DNN)")
    _truth_line(ax)
    _style_axes(ax)
    handles, labels = ax.get_legend_handles_labels()
    fig.tight_layout(rect=(0, 0.08, 1, 1))
    _legend_below(fig, handles, labels, n_panels=1, y=0.00)
    fig.savefig(savepath, dpi=200, bbox_inches="tight")
    plt.close(fig)


def plot_slide_34(df, savepath):
    fig, axes = plt.subplots(1, 2, figsize=(13.0, 4.6),
                             sharey=True, sharex=True)

    for ax, prefix in ((axes[0], "lin"), (axes[1], "nl")):
        _draw_hist(ax, df[f"{prefix}_oracle"],  C_ORACLE, "Oracle")
        _draw_hist(ax, df[f"{prefix}_dml_las"], C_LASSO,  "DML (CV-Lasso)")
        _draw_hist(ax, df[f"{prefix}_dml_dnn"], C_DNN,    "DML (DNN)")
        _truth_line(ax)
        _style_axes(ax)

    # Right panel shares y so suppress its ylabel.
    axes[1].set_ylabel("")

    handles, labels = axes[0].get_legend_handles_labels()
    fig.tight_layout(rect=(0, 0.08, 1, 1))
    _legend_below(fig, handles, labels, n_panels=2, y=0.00)
    fig.savefig(savepath, dpi=200, bbox_inches="tight")
    plt.close(fig)


def main():
    if not DATA_CSV.exists():
        raise FileNotFoundError(
            f"Expected simulation results at {DATA_CSV}. "
            f"Run InferenceOverviewSimExtended.py to regenerate."
        )

    df = pd.read_csv(DATA_CSV)
    print(f"Loaded {len(df)} reps from {DATA_CSV}")

    PLOTDIR.mkdir(parents=True, exist_ok=True)
    plot_slide_26(df, PLOTDIR / "Slide_26.png")
    plot_slide_30(df, PLOTDIR / "Slide_30.png")
    plot_slide_34(df, PLOTDIR / "Slide_34.png")
    print(f"Saved figures -> {PLOTDIR}")


if __name__ == "__main__":
    main()
